---
apiVersion: v1
kind: Namespace
metadata:
  name: app-ns
  labels:
    name: app-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  namespace: app-ns
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx-by-mpvj
        image: mpvj/test-nginx-app:1.0
        resources:
          requests:
            cpu: "1"
            memory: "100Mi"
          limits:
            cpu: "2"
            memory: "300Mi"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-app
  namespace: app-ns
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30101

---
apiVersion: v1
kind: Service
metadata:
  namespace: app-ns
  name: lb-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: port-to-app
    targetPort: 80
  # Kubernetes-метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: app